### ISSUE TITLE
Desired license?

### ISSUE THREAD

**Issue by grinnellian** [DefendPDXCode/DefendPDX-TwitterBot#6]
Might be a good idea to pick a license before code gets contributed.
I'd suggest the MIT license for max permissiveness (https://en.wikipedia.org/wiki/MIT_License), but GPL is also a popular choice which forces others using the code to keep it open-source -- a feature known as "copy-left" or "viral license" (https://en.wikipedia.org/wiki/GNU_General_Public_License).

(Apologies in advance if that's already known to whomever is behind the anonymous acct. I hope it's not patronizing)

**Comment by defendpdx** [comment]
https://github.com/DefendPDXCode/DefendPDX-TwitterBot/blob/main/LICENSE
